In [4]:
# invisible
#from IPython.display import HTML, display

import numpy as np
np.core.arrayprint._line_width = 65

## Aufgaben zum Kapitel "Numerische Operationen auf NumPy-Arrays"

### Aufgaben:

1. Aufgabe:

Gegeben sei ein Array ```B = np.array([1, 2, 3])```.

Erzeugen Sie aus diesem Array automatisch ein Array der Form:
```
[[[1 1 1]]
 [[2 2 2]]
 [[3 3 3]]]
```
Dieses Array hat die Shape  ```(3, 1, 3)```.

In [5]:
B = np.array([1, 2, 3])
print(B.shape)
B = B[np.newaxis, :]
print(B.shape)
B = np.concatenate((B, B, B)).transpose()
print(B.shape)
B = B[:, np.newaxis]
print(B.shape)
print(B)

(3,)
(1, 3)
(3, 3)
(3, 1, 3)
[[[1 1 1]]

 [[2 2 2]]

 [[3 3 3]]]


2. Aufgabe:

Erzeugen Sie ein Integer-Array A mit Shape (3, 4). Erzeugen Sie ein eindimensionales Array Z mit den jewiligen Zeilenminima und ein eindimensionales Array S mit den Spaltenminima. Wie lautet das absolute Minimum des Arrays?

In [6]:
A = np.random.randint(-10, 10, (3, 4))
print(A)

print("Zeilenminima: ")
print(np.min(A, axis=1))

print("Spaltenminima: ")
print(np.min(A, axis=0))

print("Absolutes Minimum: ")
print(np.min(A))

[[-10   5   1   1]
 [  6 -10   1  -6]
 [  9   7   1  -7]]
Zeilenminima: 
[-10 -10  -7]
Spaltenminima: 
[-10 -10   1  -7]
Absolutes Minimum: 
-10
