## Aufgaben zum Kapitel "Arrays in NumPy  erzeugen"

1. Erzeugen Sie ein beliebiges eindimensionales Array, welches Sie "v" nennen.

In [1]:
import numpy as np  
v = np.array([3,8,12,18,7,11,30])

2. Erzeugen Sie nun ein neues Array, das aus den ungeraden Indizes des vorher erzeugten Arrays "v" besteht.

In [2]:
odd_elements = v[1::2]
print(odd_elements)

[ 8 18 11]


3. Erzeugen Sie aus 'v' ein Array in umgekehrter Reihenfolge.

In [3]:
reverse_order = v[::-1]
print(reverse_order)

[30 11  7 18 12  8  3]


4. Wie sieht die Ausgabe des folgenden Codes aus?

In [4]:
a = np.array([1, 2, 3, 4, 5])
b = a[1:4]
b[0] = 200
print(a[1])

200


Die Ausgabe lautet 200, weil der Teilbereichsoperator in NumPy Sichten (Views) und keine Kopien liefert.

5. Erzeugen Sie ein zweidimensionales Array mit dem Namen "m".

In [5]:
m = np.array([ [11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 34]])
print(m)

[[11 12 13 14]
 [21 22 23 24]
 [31 32 33 34]]


6. Erzeugen Sie nun ein neues Array aus 'm', in dem die Elemente von jeder Reihe in umgekehrter Reihenfolge sind.

In [6]:
m[::,::-1]

array([[14, 13, 12, 11],
       [24, 23, 22, 21],
       [34, 33, 32, 31]])

7. Ein weiteres, in dem die Zeilen in vertauschter Reihenfolge sind.

In [7]:
m[::-1]

array([[31, 32, 33, 34],
       [21, 22, 23, 24],
       [11, 12, 13, 14]])

8. Erzeugen Sie ein Array aus m, in dem sowohl die Zeilen als auch die Spalten in umgekehrter Reihenfolge sind.

In [8]:
m[::-1,::-1]

array([[34, 33, 32, 31],
       [24, 23, 22, 21],
       [14, 13, 12, 11]])

9. Schneiden Sie die erste und die letzte Reihe und Spalte ab.

In [9]:
m[1:-1,1:-1]

array([[22, 23]])